/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	vpcv1 "kubesphere.io/api/vpc/v1"
)

// FakeVPCNetworks implements VPCNetworkInterface
type FakeVPCNetworks struct {
	Fake *FakeK8sV1
}

var vpcnetworksResource = schema.GroupVersionResource{Group: "k8s.ovn.org", Version: "v1", Resource: "vpcnetworks"}

var vpcnetworksKind = schema.GroupVersionKind{Group: "k8s.ovn.org", Version: "v1", Kind: "VPCNetwork"}

// Get takes name of the vPCNetwork, and returns the corresponding vPCNetwork object, and an error if there is any.
func (c *FakeVPCNetworks) Get(ctx context.Context, name string, options v1.GetOptions) (result *vpcv1.VPCNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(vpcnetworksResource, name), &vpcv1.VPCNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*vpcv1.VPCNetwork), err
}

// List takes label and field selectors, and returns the list of VPCNetworks that match those selectors.
func (c *FakeVPCNetworks) List(ctx context.Context, opts v1.ListOptions) (result *vpcv1.VPCNetworkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(vpcnetworksResource, vpcnetworksKind, opts), &vpcv1.VPCNetworkList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &vpcv1.VPCNetworkList{ListMeta: obj.(*vpcv1.VPCNetworkList).ListMeta}
	for _, item := range obj.(*vpcv1.VPCNetworkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vPCNetworks.
func (c *FakeVPCNetworks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(vpcnetworksResource, opts))
}

// Create takes the representation of a vPCNetwork and creates it.  Returns the server's representation of the vPCNetwork, and an error, if there is any.
func (c *FakeVPCNetworks) Create(ctx context.Context, vPCNetwork *vpcv1.VPCNetwork, opts v1.CreateOptions) (result *vpcv1.VPCNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(vpcnetworksResource, vPCNetwork), &vpcv1.VPCNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*vpcv1.VPCNetwork), err
}

// Update takes the representation of a vPCNetwork and updates it. Returns the server's representation of the vPCNetwork, and an error, if there is any.
func (c *FakeVPCNetworks) Update(ctx context.Context, vPCNetwork *vpcv1.VPCNetwork, opts v1.UpdateOptions) (result *vpcv1.VPCNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(vpcnetworksResource, vPCNetwork), &vpcv1.VPCNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*vpcv1.VPCNetwork), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVPCNetworks) UpdateStatus(ctx context.Context, vPCNetwork *vpcv1.VPCNetwork, opts v1.UpdateOptions) (*vpcv1.VPCNetwork, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(vpcnetworksResource, "status", vPCNetwork), &vpcv1.VPCNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*vpcv1.VPCNetwork), err
}

// Delete takes name of the vPCNetwork and deletes it. Returns an error if one occurs.
func (c *FakeVPCNetworks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(vpcnetworksResource, name), &vpcv1.VPCNetwork{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVPCNetworks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(vpcnetworksResource, listOpts)

	_, err := c.Fake.Invokes(action, &vpcv1.VPCNetworkList{})
	return err
}

// Patch applies the patch and returns the patched vPCNetwork.
func (c *FakeVPCNetworks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1.VPCNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(vpcnetworksResource, name, pt, data, subresources...), &vpcv1.VPCNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*vpcv1.VPCNetwork), err
}
